# Generated by Django 2.2.3 on 2019-07-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0024_auto_20190710_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataneed',
            name='themes',
            field=models.ManyToManyField(blank=True, to='data_manager.Theme'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='attribute_fields',
            field=models.ManyToManyField(blank=True, to='data_manager.AttributeInfo'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='connect_companion_layers_to',
            field=models.ManyToManyField(blank=True, help_text='Select which main layer(s) you would like to use in conjuction with this companion layer.', related_name='_layer_connect_companion_layers_to_+', to='data_manager.Layer'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='lookup_table',
            field=models.ManyToManyField(blank=True, to='data_manager.LookupInfo'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='sublayers',
            field=models.ManyToManyField(blank=True, related_name='_layer_sublayers_+', to='data_manager.Layer'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='themes',
            field=models.ManyToManyField(blank=True, to='data_manager.Theme'),
        ),
    ]
