# Generated by Django 2.2.3 on 2019-07-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0025_auto_20190710_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='wms_info',
            field=models.BooleanField(default=False, help_text='enable Feature Info requests on click'),
        ),
        migrations.AddField(
            model_name='layer',
            name='wms_info_format',
            field=models.CharField(blank=True, default=None, help_text='Available supported feature info formats', max_length=255, null=True),
        ),
    ]
