# Generated by Django 2.2.3 on 2019-11-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0027_auto_20190730_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='espis_region',
            field=models.CharField(blank=True, choices=[('Mid Atlantic', 'Mid Atlantic')], default=None, help_text='Region to search within', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='espis_search',
            field=models.CharField(blank=True, default=None, help_text='keyphrase search for ESPIS Link', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(choices=[('XYZ', 'XYZ'), ('WMS', 'WMS'), ('ArcRest', 'ArcRest'), ('radio', 'radio'), ('checkbox', 'checkbox'), ('Vector', 'Vector'), ('VectorTile', 'VectorTile'), ('placeholder', 'placeholder')], help_text='use placeholder to temporarily remove layer from TOC', max_length=50),
        ),
        migrations.AlterField(
            model_name='layer',
            name='mouseover_field',
            field=models.CharField(blank=True, default=None, help_text='feature level attribute used in mouseover display', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='point_radius',
            field=models.IntegerField(blank=True, default=None, help_text='Used only for for Point layers (default is 2)', null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='vector_color',
            field=models.CharField(blank=True, default=None, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='vector_fill',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='vector_graphic',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='vector_outline_color',
            field=models.CharField(blank=True, default=None, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='vector_outline_opacity',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
