# Generated by Django 2.2.3 on 2019-11-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0029_auto_20191107_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='vector_graphic_scale',
            field=models.FloatField(blank=True, default=True, help_text='Scale for the vector graphic from original size.', null=True, verbose_name='Vector Graphic Scale'),
        ),
        migrations.AddField(
            model_name='layer',
            name='vector_outline_width',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Vector Stroke Width'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='vector_color',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Vector Fill Color'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='vector_fill',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Vector Fill Opacity'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='vector_graphic',
            field=models.CharField(blank=True, default=None, help_text='address of image to use for point data', max_length=255, null=True, verbose_name='Vector Graphic'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='vector_outline_opacity',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Vector Stroke Opacity'),
        ),
    ]
