# Generated by Django 2.2.3 on 2019-11-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0030_auto_20191107_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookupinfo',
            name='graphic_scale',
            field=models.FloatField(blank=True, default=None, help_text='Scale the graphic from its original size.', null=True, verbose_name='Graphic Scale'),
        ),
    ]
