# Generated by Django 2.2.9 on 2020-09-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0033_layer_show_legend'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='catalog_id',
            field=models.TextField(blank=True, help_text='unique ID of associated record in catalog', null=True),
        ),
    ]
