# Generated by Django 2.2.12 on 2021-02-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0033_layer_show_legend'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='label_field',
            field=models.CharField(blank=True, help_text='Which field should be used for labels and feature identification in reports?', max_length=255, null=True),
        ),
    ]
