# Generated by Django 2.2.12 on 2021-04-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0034_layer_label_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='multilayerdimension',
            name='angle_labels',
            field=models.BooleanField(default=False, help_text='display labels at an angle to make more fit'),
        ),
    ]
