# Generated by Django 2.2.9 on 2020-09-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0034_layer_catalog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='catalog_name',
            field=models.TextField(blank=True, help_text='name of associated record in catalog', null=True, verbose_name='Catalog Record Name'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='catalog_id',
            field=models.TextField(blank=True, help_text='unique ID of associated record in catalog', null=True, verbose_name='Catalog Record Id'),
        ),
    ]
