# Generated by Django 2.2.24 on 2021-10-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0035_multilayerdimension_angle_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='query_by_point',
            field=models.BooleanField(default=False, help_text='Do not buffer selection clicks (not recommended for point or line data)'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(choices=[('XYZ', 'XYZ'), ('WMS', 'WMS'), ('ArcRest', 'ArcRest'), ('ArcFeatureServer', 'ArcFeatureServer'), ('radio', 'radio'), ('checkbox', 'checkbox'), ('Vector', 'Vector'), ('VectorTile', 'VectorTile'), ('placeholder', 'placeholder')], help_text='use placeholder to temporarily remove layer from TOC', max_length=50),
        ),
    ]
