# Generated by Django 3.2.9 on 2021-11-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0035_auto_20200911_2051'),
        ('data_manager', '0036_auto_20211021_1845'),
    ]

    operations = [
    ]
