# Generated by Django 3.2.9 on 2022-02-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0038_auto_20211216_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
