# Generated by Django 3.2.9 on 2022-02-28 21:38

from django.db import migrations, models
from datetime import datetime

def get_last_change(apps, self):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    LogEntry = apps.get_model('admin', 'LogEntry')
    layer_ct = ContentType.objects.get(model='layer')
    logs = LogEntry.objects.filter(content_type=layer_ct, object_id=self.pk)
    if len(logs) > 0:
        last_log = logs.order_by('-action_time')[0]
        return last_log.action_time
    else:
        return datetime.now()

def populate_date_modified(apps, schema_editor):
    Layer = apps.get_model('data_manager', 'Layer')
    for layer in Layer.objects.all():
        layer.date_modified = get_last_change(apps, layer)
        layer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0039_alter_layer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='date_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(populate_date_modified)
    ]
