# Generated by Django 3.2.9 on 2022-02-28 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0040_layer_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2022, 2, 28, 21, 56, 2, 836174)),
            preserve_default=False,
        ),
    ]
