# Generated by Django 3.2.12 on 2022-05-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0041_alter_layer_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookupinfo',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='lookup_field',
            field=models.CharField(blank=True, help_text='To override the style based on specific attributes, provide the attribute name here and define your attributes in the Lookup table below.', max_length=255, null=True),
        ),
    ]
