# Generated by Django 3.2.12 on 2022-08-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0045_layer_custom_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeinfo',
            name='preserve_format',
            field=models.BooleanField(default=False, help_text='Prevent portal from making any changes to the data to make it human-readable'),
        ),
    ]
