# Generated by Django 3.2.12 on 2022-08-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0046_attributeinfo_preserve_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='maxZoom',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Maximum zoom scale at which to display this layer.'),
        ),
        migrations.AddField(
            model_name='layer',
            name='minZoom',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Minimum zoom scale at which to display this layer.'),
        ),
    ]
